### ISSUE TITLE
Issues: from Team Swallows

### ISSUE THREAD

**Issue by sergiomauz** [Emmanuelaaron/News-week-clone#6]
- Consider hiding the logo in the header with d-none and d-sm-block.
- Consider adjusting the width of the footer on mobile sizes because it is overflowing the window.
- Consider wrapping the elements of the navbar at around 780px of width so that it doesn't overflow the page.
- At Ipad size the More Stories section is overlapping with the Latest News section.
- Consider using a col-* class for every div inside a row class for every direct child.
- The max length of all of the col children of a row shouldn't be greater than 12.

**Comment by Emmanuelaaron** [comment]
All have been worked on. Thanks for the feedback though
